name: Auto Stamp README (Windows)

on:
  schedule:
    # Daily around 01:05 PT (~09:05 UTC)
    - cron: "5 9 * * *"
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: auto-stamp-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stamp:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          ref: ${{ github.ref }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update README date stamp (Windows)
        id: stamp
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = 'README.md';

            if (!fs.existsSync(path)) {
              core.info('README.md not found; skipping.');
              core.setOutput('changed', 'false');
              return;
            }

            const source = fs.readFileSync(path, 'utf8');

            // Format like "September 25, 2025" in America/Los_Angeles
            const fmt = new Intl.DateTimeFormat('en-US', {
              timeZone: 'America/Los_Angeles',
              year: 'numeric',
              month: 'long',
              day: '2-digit'
            });
            const date = fmt.format(new Date());

            const updated = source.replace(/<!--AUTO-DATE-->/g, date);

            if (updated !== source) {
              fs.writeFileSync(path, updated, 'utf8');
              core.info(`README updated to: ${date}`);
              core.setOutput('changed', 'true');
            } else {
              core.info('No AUTO-DATE placeholder changed.');
              core.setOutput('changed', 'false');
            }

      - name: Commit and push (if changed)
        if: steps.stamp.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-stamp README [skip ci]"
          file_pattern: README.md
