name: Deploy Ethics Testbed to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build & prepare artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # If you commit bundle.css already, you can skip Node setup + build.
      # Keeping it here ensures consistent artifacts and catches schema errors.
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build CSS bundle
        run: npm run build:css

      - name: Validate scenarios.json
        run: npm run validate:scenarios

      # If you have an asset sync step that populates /public (HTML, JS, data)
      - name: Sync site assets to /public
        run: npm run sync

      # Ensure Pages artifact has domain + nojekyll markers INSIDE /public
      - name: Ensure CNAME and .nojekyll in artifact
        run: |
          mkdir -p public
          if [ -f CNAME ]; then cp -f CNAME public/CNAME; fi
          touch public/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
